/* Auto-generated by Guing — do not edit manually */

// mui-v7 — full library pass-through + adapter infra
// Client app never imports from 'mui-v7' directly; everything comes from here.
export * from './components/adapters/mui-v7';

// Design Tokens
export * from './design-tokens';
export * from './design-tokens/vars';

// Token-driven typography bridge — every Figma typography token becomes <Typography.XxxYyy>
export { Typography } from './components/Text/Text';

// Figma-mapped components (override library defaults for same-named exports)
export { TTT1 } from './components/TTT1';
